id: I7E7F0551
legacy_id: P006857
ocr_import_info:
  bdrc_scan_id: W2DB4547
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:12:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T16:48:11.820749+00:00'
last_modified: 2022-09-03 00:48:23.816634
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2DB4547
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2DB4547
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གནམ་འབྲུག་སེ་བ་བྱང་ཆུབ་ཆོས་གླིང་དགོན་གྱི་ངོ་སྤྲོད་མདོར་བསྡུས།
statistics:
  ocr_word_mean_confidence_index: 0.746187257625108
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG02896:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02896
      total_pages: 13
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02896.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.746187257625108
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
